package com.logi.flow.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * JPA Entity — mapped to the "users" table in PostgreSQL.
 *
 * Part of Data / Persistence Layer (Flow 11).
 *
 * Lifecycle:
 *   Spring Data JPA → Hibernate → JDBC → PostgreSQL
 *   @Transactional  → EntityManager proxied by Spring → SQL generated by Hibernate
 */
@Entity
@Table(
    name = "users",
    uniqueConstraints = @UniqueConstraint(name = "uk_users_email", columnNames = "email")
)
public class UserEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_seq")
    @SequenceGenerator(name = "users_seq", sequenceName = "users_id_seq", allocationSize = 1)
    private Long id;

    @Column(nullable = false, length = 50)
    private String name;

    @Column(nullable = false, length = 255)
    private String email;

    @Column(length = 100)
    private String department;

    /**
     * Set automatically by Hibernate on INSERT — maps INSERT timestamp to created_at column.
     * Never updated again (updatable = false).
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Set automatically by Hibernate on INSERT and every UPDATE — maps to updated_at column.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ── Constructors ──────────────────────────────────────────────────────────────

    public UserEntity() {}

    public UserEntity(String name, String email, String department) {
        this.name = name;
        this.email = email;
        this.department = department;
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getDepartment() { return department; }
    public void setDepartment(String department) { this.department = department; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    @Override
    public String toString() {
        return "UserEntity{id=" + id + ", name='" + name + "', email='" + email +
               "', department='" + department + "'}";
    }
}
